#!/bin/bash
#@SPEEDNET

mkdir -p /var/www/html/server

fun_online() {
    _ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)

    [[ -e /etc/openvpn/openvpn-status.log ]] \
        && _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log) \
        || _onop="0"

    if [[ -e /etc/default/dropbear ]]; then
        _drp=$(ps aux | grep dropbear | grep -v grep | wc -l)
        _ondrp=$((_drp - 1))
    else
        _ondrp="0"
    fi

    _onli=$((_ons + _onop + _ondrp))
    CURRENT_ONLINES=$(printf "%s" "$_onli")

    echo "{\"onlines\":\"$CURRENT_ONLINES\",\"limite\":\"1500\"}" > /var/www/html/server/online_app
    echo "$CURRENT_ONLINES" > /var/www/html/server/online
}

while true; do
    fun_online
    sleep 15
done
